### ISSUE TITLE
ionic/angular rendering error

### ISSUE THREAD

**Issue by gchokeen** [santilland/plotty#50]
I'm trying to plot geotiff in open layer, Basically following this example: https://github.com/pbabik/webraster/blob/master/index.html

I'm doing the same think in  ionic/angular latest version, unfortunately it's giving the following error.

here is the implementation 
```
    let the_canvas = this.document.createElement('canvas'); //create an offscreen canvas for rendering
    this.renderer.appendChild(this.elementRef.nativeElement, the_canvas);

    const plot = new plotty.plot({
      canvas: the_canvas,
      data: bands[0], width: image.getWidth(), height: image.getHeight(),
      domain: [minValue, maxValue],
      colorScale: 'earth',
      clampLow: true,
      clampHigh: true
    });

      plot.render();
 
```
Error
```
Uncaught TypeError: Cannot read properties of null (reading 'width')
    at e.value (plotty.min.js:8:9685)
    at ol-map.component.ts:229:12
    at timer (zone.js:3128:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:443:1)
    at Zone.push.23484.Zone.runTask (zone.js:214:1)
    at push.23484.ZoneTask.invokeTask (zone.js:525:1)
    at ZoneTask.invoke (zone.js:514:1)
    at data.args.<computed> (zone.js:3108:1)
```
I consoled the `the_canvas` and it's there!

**Comment by gchokeen** [comment]
Sorry my bad! I missed out `await` for bands `bands = image.readRasters()` so it's working now, I will close this
